add important libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_predict, KFold ,cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.dummy import DummyClassifier
%matplotlib inline

read the training data

In [4]:
data = pd.read_csv("data_train.csv")
data

label  Age  Language  Sex  Marital  Has_Credit  Field  Month_of_birth  \
0         0   34         1    2        6           2     13              12   
1         0   38         1    1        5           1     10               7   
2         0   35         1    2        4           2      9               8   
3         0   27         1    1        5           2     13               7   
4         0   32         1    2        4           2     10               7   
...     ...  ...       ...  ...      ...         ...    ...             ...   
8702      1   38         1    2        4           1     16              12   
8703      1   32         1    2        4           1      4               1   
8704      1   24         1    1        7           1      5              10   
8705      1   31         1    2        4           1      1               6   
8706      1   40         1    2        4           1      5               4   

      Day_of_birth  Region  Number_of_credits  Linked_cards  INPS_mln_sum  \
0                1      12                  1             0           0.0   
1                1      13                  1             2           0.0   
2                1      13                  4             1           1.0   
3                1      12                  1             2           1.0   
4                1      13                  3             1           2.0   
...            ...     ...                ...           ...           ...   
8702             2       9                  1             1           3.0   
8703             2      12                  1             1           1.5   
8704             1       4                  1             1           0.0   
8705             2       7                  1             1           0.0   
8706             1       2                  1             1           0.0   

      INPS_yes_no  Score_level  Score_class Score_point  Changed_phone_number  
0               0            0            0           -                     1  
1               0            0            0           -                     1  
2               1            0            0           -                     1  
3               0            0            0           -                     1  
4               1            0            0           -                     1  
...           ...          ...          ...         ...                   ...  
8702            1            0            0           0                     0  
8703            1            0            0           0                     0  
8704            0            0            0           0                     0  
8705            0            3            6         237                     0  
8706            0            3            6         263                     0  

[8707 rows x 18 columns]

describing the data

In [5]:
data.describe()

label          Age     Language          Sex      Marital  \
count  8707.000000  8707.000000  8707.000000  8707.000000  8707.000000   
mean      0.923050    37.690479     1.147468     1.622488     4.540829   
std       0.266527    10.750031     0.354592     0.484792     1.053161   
min       0.000000    19.000000     1.000000     1.000000     1.000000   
25%       1.000000    29.000000     1.000000     1.000000     4.000000   
50%       1.000000    36.000000     1.000000     2.000000     4.000000   
75%       1.000000    44.000000     1.000000     2.000000     5.000000   
max       1.000000    79.000000     2.000000     2.000000     7.000000   

        Has_Credit        Field  Month_of_birth  Day_of_birth       Region  \
count  8707.000000  8707.000000     8707.000000   8707.000000  8707.000000   
mean      1.032043    10.485012        6.360859      1.462157    11.207190   
std       0.176125     5.597442        3.405988      0.498594     3.020191   
min       1.000000     0.000000        1.000000      1.000000     0.000000   
25%       1.000000     6.000000        3.000000      1.000000    12.000000   
50%       1.000000    13.000000        6.000000      1.000000    12.000000   
75%       1.000000    14.000000        9.000000      2.000000    13.000000   
max       2.000000    22.000000       12.000000      2.000000    14.000000   

       Number_of_credits  Linked_cards  INPS_mln_sum  INPS_yes_no  \
count        8707.000000   8707.000000   8707.000000  8707.000000   
mean            1.119789      1.100838      2.132932     0.957505   
std             0.366915      0.315294      2.225331     0.201726   
min             1.000000      0.000000      0.000000     0.000000   
25%             1.000000      1.000000      1.000000     1.000000   
50%             1.000000      1.000000      1.700000     1.000000   
75%             1.000000      1.000000      2.800000     1.000000   
max             5.000000      4.000000     86.300000     1.000000   

       Score_level  Score_class  Changed_phone_number  
count  8707.000000  8707.000000           8707.000000  
mean      0.547491     1.082807              0.112094  
std       1.190702     2.447644              0.344394  
min       0.000000     0.000000              0.000000  
25%       0.000000     0.000000              0.000000  
50%       0.000000     0.000000              0.000000  
75%       0.000000     0.000000              0.000000  
max       4.000000    11.000000              3.000000

show first 5 rows

In [6]:
data.head()

label  Age  Language  Sex  Marital  Has_Credit  Field  Month_of_birth  \
0      0   34         1    2        6           2     13              12   
1      0   38         1    1        5           1     10               7   
2      0   35         1    2        4           2      9               8   
3      0   27         1    1        5           2     13               7   
4      0   32         1    2        4           2     10               7   

   Day_of_birth  Region  Number_of_credits  Linked_cards  INPS_mln_sum  \
0             1      12                  1             0           0.0   
1             1      13                  1             2           0.0   
2             1      13                  4             1           1.0   
3             1      12                  1             2           1.0   
4             1      13                  3             1           2.0   

   INPS_yes_no  Score_level  Score_class Score_point  Changed_phone_number  
0            0            0            0           -                     1  
1            0            0            0           -                     1  
2            1            0            0           -                     1  
3            0            0            0           -                     1  
4            1            0            0           -                     1

see if there is any null values


In [7]:
data.isnull().sum()

label                   0
Age                     0
Language                0
Sex                     0
Marital                 0
Has_Credit              0
Field                   0
Month_of_birth          0
Day_of_birth            0
Region                  0
Number_of_credits       0
Linked_cards            0
INPS_mln_sum            0
INPS_yes_no             0
Score_level             0
Score_class             0
Score_point             0
Changed_phone_number    0
dtype: int64

 view the information of the data

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8707 entries, 0 to 8706
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   label                 8707 non-null   int64  
 1   Age                   8707 non-null   int64  
 2   Language              8707 non-null   int64  
 3   Sex                   8707 non-null   int64  
 4   Marital               8707 non-null   int64  
 5   Has_Credit            8707 non-null   int64  
 6   Field                 8707 non-null   int64  
 7   Month_of_birth        8707 non-null   int64  
 8   Day_of_birth          8707 non-null   int64  
 9   Region                8707 non-null   int64  
 10  Number_of_credits     8707 non-null   int64  
 11  Linked_cards          8707 non-null   int64  
 12  INPS_mln_sum          8707 non-null   float64
 13  INPS_yes_no           8707 non-null   int64  
 14  Score_level           8707 non-null   int64  
 15  Score_class          

view score point columns

In [9]:
data['Score_point']

0         -
1         -
2         -
3         -
4         -
       ... 
8702      0
8703      0
8704      0
8705    237
8706    263
Name: Score_point, Length: 8707, dtype: object

we need to repalce the - with 0

In [10]:
data = data.replace({'-':0})

In [11]:
data['Score_point']

0         0
1         0
2         0
3         0
4         0
       ... 
8702      0
8703      0
8704      0
8705    237
8706    263
Name: Score_point, Length: 8707, dtype: object

we will split  the data set into x and y as dependent and independent values

In [12]:
y = data['Score_class']
X = data.drop(['Score_class'], axis=1, inplace=False)

view x

In [13]:
X

label  Age  Language  Sex  Marital  Has_Credit  Field  Month_of_birth  \
0         0   34         1    2        6           2     13              12   
1         0   38         1    1        5           1     10               7   
2         0   35         1    2        4           2      9               8   
3         0   27         1    1        5           2     13               7   
4         0   32         1    2        4           2     10               7   
...     ...  ...       ...  ...      ...         ...    ...             ...   
8702      1   38         1    2        4           1     16              12   
8703      1   32         1    2        4           1      4               1   
8704      1   24         1    1        7           1      5              10   
8705      1   31         1    2        4           1      1               6   
8706      1   40         1    2        4           1      5               4   

      Day_of_birth  Region  Number_of_credits  Linked_cards  INPS_mln_sum  \
0                1      12                  1             0           0.0   
1                1      13                  1             2           0.0   
2                1      13                  4             1           1.0   
3                1      12                  1             2           1.0   
4                1      13                  3             1           2.0   
...            ...     ...                ...           ...           ...   
8702             2       9                  1             1           3.0   
8703             2      12                  1             1           1.5   
8704             1       4                  1             1           0.0   
8705             2       7                  1             1           0.0   
8706             1       2                  1             1           0.0   

      INPS_yes_no  Score_level Score_point  Changed_phone_number  
0               0            0           0                     1  
1               0            0           0                     1  
2               1            0           0                     1  
3               0            0           0                     1  
4               1            0           0                     1  
...           ...          ...         ...                   ...  
8702            1            0           0                     0  
8703            1            0           0                     0  
8704            0            0           0                     0  
8705            0            3         237                     0  
8706            0            3         263                     0  

[8707 rows x 17 columns]

view y

In [14]:
y

0       0
1       0
2       0
3       0
4       0
       ..
8702    0
8703    0
8704    0
8705    6
8706    6
Name: Score_class, Length: 8707, dtype: int64

we will split the dataset into training and testing


In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.30)

view the shape of x train and x test

In [16]:
print(X_train.shape, X_test.shape)

(6094, 17) (2613, 17)


view the shape of y train and y test

In [17]:
print(y_train.shape, y_test.shape)

(6094,) (2613,)





*   we will use LogisticRegression as a binary classification to predict the output
*   we will also use cross validation to assess the preformance of the model
*   we will use radom state = 150


In [18]:
num_folds = 5
model = LogisticRegression()
kf = KFold(n_splits=num_folds, shuffle=True, random_state=150)
cross_val_predictions = cross_val_predict(model, X_train, y_train, cv=kf)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c



*   we will calulate the accuracy
*   we will calulate the confusion matrix
*   we will calulate the classification report



In [19]:
accuracy_cv = accuracy_score(y_train, cross_val_predictions)
conf_matrix_cv = confusion_matrix(y_train, cross_val_predictions)
class_report_cv = classification_report(y_train, cross_val_predictions)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



*   we will print the accuracy
*   we will print the confusion matrix
*   we will print the classification report

In [20]:
print('accuracy')
print(accuracy_cv)

print('conf matrix')
print(conf_matrix_cv)

print('class report')
print(class_report_cv)

accuracy
0.9309156547423696
conf matrix
[[5038    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0  128    0    0    0    0]
 [   0    0    0    0    0    0   10    0    0    0    0]
 [   0    0    0    0    0    0    1    0    0    0    0]
 [   0    0    0    0   47   21   32    0    0    2    0]
 [   0    1    0    0   12   17  158    0    0    1    0]
 [   0    3    0    0    9    5  570    0    0    0    0]
 [   0    0    0    0    3    0    0    0    0    0    0]
 [   0    0    0    0    8    0    0    0    0    1    0]
 [   0    0    0    0   17    3    5    0    0    1    0]
 [   0    0    0    0    0    0    0    0    1    0    0]]
class report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5038
           2       0.00      0.00      0.00       128
           3       0.00      0.00      0.00        10
           4       0.00      0.00      0.00         1
           5       0.49      0.46    

we will make a dummy model to see cross validation score

In [21]:
dummy_classifier = DummyClassifier()
dummy_classifier.fit(X_train, y_train)
dummy_predictions = dummy_classifier.predict(X_test)

In [22]:
cv_scores = cross_val_score(dummy_classifier, X_train, y_train, cv=3)
print("Cross-Validation Scores:", cv_scores)
print("Mean CV Score:", cv_scores.mean())

Cross-Validation Scores: [0.82677165 0.82668636 0.82668636]
Mean CV Score: 0.8267147921133197


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


now we will compare between actual data and predicting data

In [23]:
result_df = pd.DataFrame({'Actual': y_train, 'Predicted': cross_val_predictions})

# Display the DataFrame for the entire dataset
print("Results on Entire Dataset:")
print(result_df.head(50))

Results on Entire Dataset:
      Actual  Predicted
1548       0          0
6135       0          0
2449       0          0
3577       0          0
4208       0          0
3105       0          0
8207       0          0
7935       7          7
6566      10          5
7148       0          0
3951       7          7
7212       0          0
123        0          0
5361       0          0
5822       0          0
6925       0          0
5630       0          0
3601       0          0
3774       0          0
7226       0          0
1907       0          0
3718       0          0
8331       0          0
2412       0          0
8061       7          7
2989       0          0
8321       0          0
7004       0          0
6093       7          7
5246       0          0
4524       0          0
2440       0          0
8226       5          7
821        0          0
6173       0          0
714        0          0
7101       0          0
5797       0          0
1123       0          0
274        0 

now we will use test data set to test the model

we will read and view the test dataset

In [24]:
test = pd.read_csv('data_test.csv')
test

label  Age  Language  Sex  Marital  Has_Credit  Field  Month_of_birth  \
0       0   40         1    2        4           1      0               3   
1       0   36         2    2        4           1      0               5   
2       0   31         1    2        4           1      0               7   
3       0   29         1    2        4           1      0               1   
4       0   38         1    2        4           1      0              10   
5       0   33         1    2        4           1      0               9   
6       0   34         1    1        5           1      0               4   
7       0   28         1    2        4           1      0               8   
8       0   33         1    1        5           1      0               6   
9       0   35         1    1        5           1      0              10   
10      0   25         1    2        6           1      0               4   
11      0   29         1    2        4           1      0               5   
12      0   34         1    1        5           1      0               9   
13      0   24         1    2        6           1      0              11   
14      0   51         2    1        2           1      0              11   
15      0   47         1    2        4           1      0              11   
16      0   57         1    2        3           1      0               8   
17      0   33         1    2        6           1      0              10   
18      0   36         1    2        4           1      0               8   
19      0   22         1    2        6           1      0               1   
20      0   27         1    2        6           1      0               7   
21      0   44         1    2        4           1      0              10   
22      0   26         1    2        6           1      0               9   
23      0   35         1    2        4           1      0               7   
24      0   26         1    2        6           1      0               8   
25      0   29         1    2        6           1      0               3   
26      1   38         1    1        5           1     10               5   
27      1   56         1    2        4           1     14               2   
28      1   48         1    2        4           1     13               8   
29      1   51         1    2        4           1      2               1   
30      1   56         1    1        5           1      2               8   
31      1   69         1    1        5           1     20              10   
32      1   43         2    2        4           1     11               6   
33      1   38         2    1        5           1     11               1   
34      1   52         2    1        2           1     13               8   
35      1   31         1    2        6           1      3              10   
36      1   35         1    2        4           1      4               7   
37      1   48         1    1        1           1     16               8   
38      1   34         1    2        4           1      4               1   
39      1   29         1    1        7           1     13              10   
40      1   31         1    1        5           1     16               3   
41      1   37         1    1        5           1     13               1   
42      1   54         1    2        4           1      1               3   
43      1   66         1    1        5           1     10               6   
44      1   33         1    1        7           1     10               7   
45      1   42         1    2        4           1      7               2   
46      1   36         1    2        4           1     16              12   
47      1   26         2    2        6           1      1               2   

    Day_of_birth  Region  Number_of_credits  Linked_cards  INPS_mln_sum  \
0              1      12                  2             1           2.4   
1              1      13                  1             2           0.0   
2    

print shape of the dataset

In [25]:
test.shape

(48, 18)

In [26]:
test = test.replace({'-':0})

In [27]:
test

label  Age  Language  Sex  Marital  Has_Credit  Field  Month_of_birth  \
0       0   40         1    2        4           1      0               3   
1       0   36         2    2        4           1      0               5   
2       0   31         1    2        4           1      0               7   
3       0   29         1    2        4           1      0               1   
4       0   38         1    2        4           1      0              10   
5       0   33         1    2        4           1      0               9   
6       0   34         1    1        5           1      0               4   
7       0   28         1    2        4           1      0               8   
8       0   33         1    1        5           1      0               6   
9       0   35         1    1        5           1      0              10   
10      0   25         1    2        6           1      0               4   
11      0   29         1    2        4           1      0               5   
12      0   34         1    1        5           1      0               9   
13      0   24         1    2        6           1      0              11   
14      0   51         2    1        2           1      0              11   
15      0   47         1    2        4           1      0              11   
16      0   57         1    2        3           1      0               8   
17      0   33         1    2        6           1      0              10   
18      0   36         1    2        4           1      0               8   
19      0   22         1    2        6           1      0               1   
20      0   27         1    2        6           1      0               7   
21      0   44         1    2        4           1      0              10   
22      0   26         1    2        6           1      0               9   
23      0   35         1    2        4           1      0               7   
24      0   26         1    2        6           1      0               8   
25      0   29         1    2        6           1      0               3   
26      1   38         1    1        5           1     10               5   
27      1   56         1    2        4           1     14               2   
28      1   48         1    2        4           1     13               8   
29      1   51         1    2        4           1      2               1   
30      1   56         1    1        5           1      2               8   
31      1   69         1    1        5           1     20              10   
32      1   43         2    2        4           1     11               6   
33      1   38         2    1        5           1     11               1   
34      1   52         2    1        2           1     13               8   
35      1   31         1    2        6           1      3              10   
36      1   35         1    2        4           1      4               7   
37      1   48         1    1        1           1     16               8   
38      1   34         1    2        4           1      4               1   
39      1   29         1    1        7           1     13              10   
40      1   31         1    1        5           1     16               3   
41      1   37         1    1        5           1     13               1   
42      1   54         1    2        4           1      1               3   
43      1   66         1    1        5           1     10               6   
44      1   33         1    1        7           1     10               7   
45      1   42         1    2        4           1      7               2   
46      1   36         1    2        4           1     16              12   
47      1   26         2    2        6           1      1               2   

    Day_of_birth  Region  Number_of_credits  Linked_cards  INPS_mln_sum  \
0              1      12                  2             1           2.4   
1              1      13                  1             2           0.0   
2    

In [28]:
New_Y = test['Score_class']
New_X = test.drop(['Score_class'], axis=1, inplace=False)

In [29]:
New_X.head()

label  Age  Language  Sex  Marital  Has_Credit  Field  Month_of_birth  \
0      0   40         1    2        4           1      0               3   
1      0   36         2    2        4           1      0               5   
2      0   31         1    2        4           1      0               7   
3      0   29         1    2        4           1      0               1   
4      0   38         1    2        4           1      0              10   

   Day_of_birth  Region  Number_of_credits  Linked_cards  INPS_mln_sum  \
0             1      12                  2             1           2.4   
1             1      13                  1             2           0.0   
2             1      13                  1             1           0.3   
3             1      13                  1             1           0.9   
4             1      13                  1             2           4.3   

   INPS_yes_no  Score_level Score_point  Changed_phone_number  
0            1            0           0                     1  
1            1            0           0                     1  
2            0            0           0                     2  
3            1            0           0                     1  
4            0            4         318                     1

In [30]:
New_Y.head()

0    0
1    0
2    0
3    0
4    2
Name: Score_class, dtype: int64

we will import cross_val_predict and KFold to view predictions

In [31]:
from sklearn.model_selection import cross_val_predict, KFold

In [32]:
num_folds = 5
cross_val_predictions_new_data = cross_val_predict(model, New_X, New_Y, cv=num_folds)
accuracy_cv_new_data = accuracy_score(New_Y, cross_val_predictions_new_data)
conf_matrix_cv_new_data = confusion_matrix(New_Y, cross_val_predictions_new_data)
class_report_cv_new_data = classification_report(New_Y, cross_val_predictions_new_data)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modu

* *we will print the accuracy
* we will print the confusion matrix
* we will print the classification report

In [33]:
print(f"Cross-Validated Accuracy on New Data: {accuracy_cv_new_data:.3f}")
print("\nConfusion Matrix (New Data):")
print(conf_matrix_cv_new_data)
print("\nClassification Report (New Data):")
print(class_report_cv_new_data)

Cross-Validated Accuracy on New Data: 0.917

Confusion Matrix (New Data):
[[39  0  0  0  0  0]
 [ 0  0  0  1  0  0]
 [ 0  0  1  0  0  1]
 [ 0  1  0  2  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  1  0  0  0]]

Classification Report (New Data):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        39
           2       0.00      0.00      0.00         1
           5       0.50      0.50      0.50         2
           6       0.67      0.67      0.67         3
           7       1.00      1.00      1.00         2
           8       0.00      0.00      0.00         1

    accuracy                           0.92        48
   macro avg       0.53      0.53      0.53        48
weighted avg       0.92      0.92      0.92        48



In [34]:
result_df = pd.DataFrame({'Actual': New_Y, 'Predicted': cross_val_predictions_new_data})

# Display the DataFrame for the entire dataset
print("Results on Entire Dataset:")
print(result_df.head(47))

Results on Entire Dataset:
    Actual  Predicted
0        0          0
1        0          0
2        0          0
3        0          0
4        2          6
5        6          2
6        0          0
7        0          0
8        8          5
9        0          0
10       0          0
11       0          0
12       0          0
13       0          0
14       0          0
15       0          0
16       5          8
17       0          0
18       0          0
19       0          0
20       7          7
21       0          0
22       0          0
23       0          0
24       0          0
25       7          7
26       0          0
27       0          0
28       0          0
29       0          0
30       0          0
31       5          5
32       0          0
33       0          0
34       0          0
35       0          0
36       0          0
37       0          0
38       0          0
39       6          6
40       6          6
41       0          0
42       0          0
43   

we will print the true predictions and false predictions

In [35]:
count = 0
count2 = 0
for i in range(len(cross_val_predictions_new_data)):
    if cross_val_predictions_new_data[i] == New_Y[i]:
        count += 1
        print(f"Prediction at index {i} is true")
    else :
        count2 += 1
        print(f"Prediction at index {i} is false")

# Print the total count
print(f"Total count of true predictions: {count}")
print(f"Total count of false predictions: {count2}")


Prediction at index 0 is true
Prediction at index 1 is true
Prediction at index 2 is true
Prediction at index 3 is true
Prediction at index 4 is false
Prediction at index 5 is false
Prediction at index 6 is true
Prediction at index 7 is true
Prediction at index 8 is false
Prediction at index 9 is true
Prediction at index 10 is true
Prediction at index 11 is true
Prediction at index 12 is true
Prediction at index 13 is true
Prediction at index 14 is true
Prediction at index 15 is true
Prediction at index 16 is false
Prediction at index 17 is true
Prediction at index 18 is true
Prediction at index 19 is true
Prediction at index 20 is true
Prediction at index 21 is true
Prediction at index 22 is true
Prediction at index 23 is true
Prediction at index 24 is true
Prediction at index 25 is true
Prediction at index 26 is true
Prediction at index 27 is true
Prediction at index 28 is true
Prediction at index 29 is true
Prediction at index 30 is true
Prediction at index 31 is true
Prediction at 

it seems that the model is doing good with accuracy of 91% and only 4 false predictions